version: '3'

services:
  escargot:
    image: ghcr.io/ondocker/escargot-server:master
    #build: .
    volumes:
      - ./data:/data
    ports:
      # MSN Messenger
      - 1863:1863
      - 1864:1864
      # IRC
      - 6667:6667
